### ISSUE TITLE
No styles on home

### ISSUE THREAD

**Issue by deveti** [Proxeuse/fortify-tabler#5]
Hi, 

when I install this package (fresh laravel) I see the applied CSS on login/register, but when I log in and enter the dashboard, it is completely without styles. I followed the instructions and I have the latest version of the plugin.

![Screenshot 2021-05-16 221336](https://user-images.githubusercontent.com/13333098/118411275-99aea100-b68b-11eb-8c0e-dfa37cfb0646.png)

Can you help me?

Best regards,
deveti

**Comment by roelreijneveld** [comment]
Could you please run the command `php artisan route:list` and post the output?
I expect that a wrong blade template is being loaded.

**Comment by deveti** [comment]
Hey, you are correct. I've managed to fix it. There are also some routes inside the templates that I needed to comment out. I think the installer did not copy all the files or something. Thank you.

**Comment by roelreijneveld** [comment]
Great! I will look into the problem later. Closing this for now.

**Comment by drewwalton19216801** [comment]
Also encountering this issue.

- views/dashboard.blade.php extends layouts.app instead of layouts.dashboard
- layouts/dashboard.blade.php seems to be trying to load a lot of css and js files that don't exist
- layouts/dashboard.blade.php contains a navbar brand link to route('home') which is an invalid route

Missing files:
- the entire dist/libs/fullcalendar directory
- dist/css/tabler-buttons.min.css (this doesn't even exist in the official tabler.io distribution)
